4주차 Review PR
kakao-tech-campus-2nd-step3/Team14_FE pull request #20
Opened 2024-09-27 14:33 UTC by minji2219

## ✨ PR 내용

💻민지: 캐러셸 구현 https://github.com/kakao-tech-campus-2nd-step3/Team14_FE/issues/11
💻호정: 라우팅 설정 https://github.com/kakao-tech-campus-2nd-step3/Team14_FE/issues/10
💻지환: button, input 공통 컴포넌트 생성, 소개페이지 구현 https://github.com/kakao-tech-campus-2nd-step3/Team14_FE/issues/12 https://github.com/kakao-tech-campus-2nd-step3/Team14_FE/issues/14

## ✏ 리뷰받고 싶은 내용
1. Button과 InputField 컴포넌트를 구현해보았는데 prop 구조가 적절하게 설계되었는지 피드백 부탁드립니다!!
2. 소개 페이지의 레이아웃이 적절하게 구현되었는지 피드백 부탁드립니다.
3. 무한 슬라이드 구현 방법과 자동으로 넘어가는 구현의 방법을 이런식으로 구현해도 괜찮은지 피드백 부탁드립니다.

2024-09-28 10:53 UTC, yujo11 requested changes
안녕하세요 ~

전체적으로 추가 구현 된 내용이 많지 않아 소소한 코멘트 위주로 남겼는데 확인해보시면 좋을거 같습니다 ㅎㅎ

>Button과 InputField 컴포넌트를 구현해보았는데 prop 구조가 적절하게 설계되었는지 피드백 부탁드립니다!!

이 부분은 코멘트로 남긴 내용 확인해주세요 ~

>소개 페이지의 레이아웃이 적절하게 구현되었는지 피드백 부탁드립니다.

적절하게 구현된거 같습니다 ~

>무한 슬라이드 구현 방법과 자동으로 넘어가는 구현의 방법을 이런식으로 구현해도 괜찮은지 피드백 부탁드립니다. 또, 현업에서 주로 슬라이드를 직접 구현하는지 라이브러리를 사용하는지 궁금합니다!

라이브러리 없이 잘 구현해주신거 같아요 ㅎㅎ 라이브러리는 swiper나 react-slick 같은걸 많이 사용하는거 같더라구요 제가 직접 구현해 본 경험은 없어 깊이는 모르겠네요

---

PR에 궁금하신 점들을 남겨주신 부분은 아주 좋은데요. 질문이 다소 추상적이라 저도 추상적인 답변 밖에 드리지 못해 조금 아쉬웠어요.

조금 더 구체적인 상황설명과 함께 어떤 의도로 구현을 했고 어떤 부분이 고민 되었는지 같이 남겨주시면 보다 도움되는 답변을 받으 실 수 있을거라고 생각합니다 ㅎㅎ

---

고생 많으셨습니다 ~~ 👍

2024-09-28 10:53 UTC, yujo11 commented on public/index.html
>      <link rel="apple-touch-icon" href="%PUBLIC_URL%/logo192.png" />
👍 👍 👍

2024-09-28 10:53 UTC, yujo11 commented on src/components/common/Button/Button.tsx
> +const Button: React.FC<ButtonProps> = ({
Button 컴포넌트는 html의 `<button>`엘리먼트를 대신해서 애플리케이션 전체에 사용 될 요소로 보이는데요. 그렇다면 html button 태그에서 사용할 수 있는 prop들을 모두 받을 수 있는 형태로 만들어주시면 좋을거 같아요 

```ts
interface ButtonProps extends HTMLButtonElement
```

2024-09-28 10:53 UTC, yujo11 commented on src/components/common/Input/InputField.tsx
> +interface InputFieldProps {
input도 마찬가지입니다 ~~

2024-09-28 10:53 UTC, yujo11 commented on src/components/common/Input/InputField.tsx
> +  border: 1px solid #e0e0e0;
이런 색상들은 별도 변수로 정의해서 사용하시면 애플리케이션 전체에 일관된 스타일을 적용하는데 도움이 되실거에요

2024-09-28 10:53 UTC, yujo11 commented on src/components/common/Modal/AlertDialog.tsx
> +const Button = styled.div((props: { cancle?: boolean }) => ({
이 styled component는 이번에 만든 Button 컴포넌트로 대체가 가능할까요?

2024-09-28 10:53 UTC, yujo11 commented on src/components/features/Layout/Header.tsx
>  const Wrapper = styled.header`
이런 styled component들은 항상 같은 파일에 위치하는게 팀 내 컨벤션인가요?

2024-09-28 10:53 UTC, yujo11 commented on src/styles/globalStyle.ts
>    },
👍 👍 👍

2024-09-28 10:53 UTC, yujo11 commented on src/components/spot/swiper/index.tsx
> +    // gap: '10px',
사용하지 않는 코드들은 커밋 전에 정리해주시면 좋을거 같네요

2024-09-29 06:41 UTC, minji2219 commented on src/components/common/Modal/AlertDialog.tsx
> +const Button = styled.div((props: { cancle?: boolean }) => ({
넵! 대체하도록 하겠습니다!

2024-09-29 06:42 UTC, minji2219 commented on src/components/features/Layout/Header.tsx
>  const Wrapper = styled.header`
넵 같은 파일 하단에 위치하도록 설정했습니다. 별도의 파일로 관리하는 것이 더 좋은 방법일까요?

2024-09-30 08:49 UTC, yujo11 commented on src/components/features/Layout/Header.tsx
>  const Wrapper = styled.header`
스타일이 많아지면 코드를 확인하기 힘들어져 저는 분리하는걸 선호하는 편입니다 ㅎㅎ

정답이 존재하는 부분은 아니니 팀 내 컨벤션 대로 유지하시다가 나중에 불편함을 느끼시면 그 때 어떻게 두는게 좋을지 고민해보셔도 좋을거 같아요 ~

2024-09-30 08:49 UTC, merged