5주차 Review PR
kakao-tech-campus-2nd-step3/Team14_FE pull request #31
Opened 2024-10-04 13:39 UTC by minji2219

## ✨ PR 내용

💻민지: 캐러셸 css 적용, 지도 연결 #11 #22 
💻호정: 라우팅 수정 및 주문 내역 생성 #23 #24 
💻지환: 폰트 적용 #25 

## ✏ 리뷰받고 싶은 내용

1. 카카오지도 api 연결
카카오지도 api를 연결했습니다. 헤더의 '내 동네 설정' 클릭시 현재 내 위치를 가져와서 지도에서 보여주게 설정했습니다.
한번 내 동네 설정 클릭 후에는 쿠키에 해당 위도, 경도를 저장해서 별도로# ✨ PR 내용

💻민지: 캐러셸 css 적용, 지도 연결 #11 #22 
💻호정: 라우팅 수정 및 주문 내역 생성 #23 #24 
💻지환: 폰트 적용 #25 

## ✏ 리뷰받고 싶은 내용

1. 카카오지도 api 연결
카카오지도 api를 연결했습니다. 헤더의 '내 동네 설정' 클릭시 현재 내 위치를 가져와서 지도에서 보여주게 설정했습니다.
- 한번 내 동네 설정 클릭 후에는 쿠키에 해당 위도, 경도를 저장해서 별도로 다시 위치 정보를 가져오지 않으면 전에 인증했던 위치로 가져오는 것이 나을까요?
- 아니면, useEffect로 한번 위치 정보 수집 허용이 됐으면, 사이트 들어 올 때 마다 현 위치를 새로 세팅 하는게 나을까요?

2024-10-05 10:48 UTC, yujo11 requested changes
안녕하세요 ~ 

이번 주는 코드 레벨에서 코멘트 남길 내용이 많지 않네요 ㅎㅎ 

>카카오지도 api 연결

이건 유저에게 어떤 사용성을 주느냐에 따라 달라질거 같은데요. 만드시려는 서비스가 배달과 관련 된 내용인만큼 다른 배달앱들의 동작을 참고해보셔도 좋을거 같아요

ex) 배달의민족의 경우 애플리케이션 접속 시, 유저의 위치를 가져와서 배달지 주소와 유저의 위치가 다르면 유저에게 현재 배달을 시킬 주소가 맞는지 확인 함

고생 많으셨습니다 ~~

2024-10-05 10:48 UTC, yujo11 commented on src/components/spot/swiper/index.tsx
> +          );
아래처럼 작성해 볼 수도 있을거 같네요

가급적이면 `let`을 사용하지 않고 작성해보시는걸 추천 드리고 싶습니다 ㅎㅎ

```suggestion
          return (
            <SlideItem
              key={store.key}
              category={store.category}
              title={store.storeName}
              address={store.pickUpLocation}
              center={index === slideNumber}
              endSlide={isEndSlide}
            />
          );
```

2024-10-05 10:48 UTC, yujo11 commented on src/routes/index.tsx
> +    path: RouterPath.root,
path는 필수값이 아니고 `root`와 `introduce`의 path가 동일해서 여기 path를 지우고

2024-10-05 10:48 UTC, yujo11 commented on src/routes/index.tsx
> +      },
아래처럼 변경해줘도 될거 같네요
```suggestion
      {
        index: true
        element: <IntroducePage />,
      },
```

2024-10-06 07:27 UTC, hojeong26 commented on src/routes/index.tsx
> +      },
오호 피드백 감사합니다!

2024-10-06 12:15 UTC, minji2219 commented on src/components/spot/swiper/index.tsx
> +          );
아하 넵 ! 간단히 처리 되네용...

2024-10-07 11:15 UTC, yujo11 approved these changes

2024-10-07 11:15 UTC, merged