6주차 Reveiw PR
kakao-tech-campus-2nd-step3/Team14_FE pull request #44
Opened 2024-10-11 14:40 UTC by minji2219

## ✨ PR 내용

💻민지: 스팟페이지구현 https://github.com/kakao-tech-campus-2nd-step3/Team14_FE/issues/38
💻호정: 프로필, 포인트 페이지 구현 https://github.com/kakao-tech-campus-2nd-step3/Team14_FE/issues/32 https://github.com/kakao-tech-campus-2nd-step3/Team14_FE/issues/33
💻지환: 피드백 반영, 로그인/회원정보 입력 페이지 구현 https://github.com/kakao-tech-campus-2nd-step3/Team14_FE/issues/34

## ✏ 리뷰받고 싶은 내용
- 지도 위도 경도 저장 방법
현재 위도, 경도를 localstorage에 저장하고 바로 반영하기 위해 context api를 사용하고 있는데 이렇게 사용하는 방법이 맞는지 잘 모르겠습니다...!
![image](https://github.com/user-attachments/assets/2a94e2ee-5bae-426b-ba05-b419f6ec30e6)
그리고 이런식으로 useEffect를 사용하면 왜 계속 변했다고 감지하고 무한 useEffect가 실행되게 될까요..?

2024-10-12 09:25 UTC, yujo11 requested changes
안녕하세요 ~ 

context의 기본 사용법에는 맞게 잘 사용해주시고 계신거 같은데요 

아래 글을 한번 참고해서 어떤 부분을 다르게 작성했는지 보시는 것도 도움이 될거 같아요

- [다른 사람들이 안 알려주는 리액트에서 Context API 잘 쓰는 방법](https://velog.io/@velopert/react-context-tutorial) 


>useEffect를 사용하면 왜 계속 변했다고 감지하고 무한 useEffect가 실행되게 될까요..?

JSON.parse로 인해 매번 새로운 객체가 생성되면서 발생하는 문제가 의심 되는데요.

이전 값과 같으면 새로운 객체가 정의 되지 않도록 아래처럼 메모이제이션을 한번 시도해보셔도 좋을거 같습니다

```tsx
const currentLocation = useMemo(() => {
  return JSON.parse(localStorage.getItem('location') as string);
}, []);
```

이번 주도 고생 많으셨습니다 ㅎㅎ

2024-10-12 09:25 UTC, yujo11 commented on src/components/common/Background/index.tsx
> +`;
이렇게 `props`으로 인한 분기가 많아질 때는 코드가 눈에 잘 들어오지 않게 되는데요 아래 같은 형식으로 style mapper를 만들어 적용해보셔도 좋을거 같네요 ㅎㅎ

```tsx
export const Box = styled.div(
  (props: BoxProps) => css`
    display: flex;
    ${alignMapper(props.direction)}
  `
);

const alignMapper = (direction: StyledBoxType['direction']) => {
  switch (direction) {
    case 'vertical':
      return css({
        flexDirection: 'column',
      });

    case 'horizontal':
    default:
      return css({
        flexDirection: 'row',
      });
  }
};

```

2024-10-12 09:25 UTC, yujo11 commented on src/components/common/Background/index.tsx
> +        <Image src="/image/motocycle.png" alt="오토바이 이미지" />
이미지 태그는 스크린 리더가 읽을 때 이미 "이미지"라는 정보를 알고 있어서 `alt`에 "이미지"라고 다시 명시할 필요가 없으니 참고하시면 좋겠네요 ㅎㅎ

2024-10-12 09:25 UTC, yujo11 commented on src/components/common/Button/index.tsx
> +  bgColor = '#ffd500',
이런 색상은 한 군데에서 모아서 관리하면 일관성 있게 전체 애플리케이션 스타일을 적용하는데 도움이 될거 같네요

2024-10-12 09:25 UTC, yujo11 commented on src/components/spot/map/index.tsx
>    return (
소소하지만 개행을 적절히 섞어주시면 코드 보기가 한결 좋아질거 같네요 ㅎㅎ

2024-10-12 09:25 UTC, yujo11 commented on src/components/spot/storelist/index.tsx
> +    category === '카테고리 선택'
"카테고리 선택" 같은 문자열은 변하기 쉬운 요소인데요. 사용하는 곳에서 실수가 발생하지 않도록 상수나 Enum으로 만들어서 관리해보시면 좋을거 같아요

2024-10-12 09:25 UTC, yujo11 commented on src/components/spot/map/index.tsx
> +        content={<div></div>}
여긴 아직 코드가 작성되지 않은거죠?

2024-10-12 09:25 UTC, yujo11 commented on src/routes/index.tsx
>        },
👍 👍 👍

2024-10-12 09:25 UTC, yujo11 commented on src/provider/Location/index.tsx
> +      localStorage.getItem('location') ||
소소하게 이런 `key`값으로 사용되는 값들은 상수로 선언해서 사용하면 휴먼 에러를 줄이는데 도움이 될거 같아요

2024-10-12 09:25 UTC, yujo11 commented on src/pages/PointPage/index.tsx
> +  const [pointFilterValue, setPointFilterValue] = useState('충전');
이런 값들도 타입스크립트의 도움을 받을 수 있게 작성해보시면 좋을거 같아요

ex)

```tsx
type PointFilter = "충전" | "결제"

const [pointFilterValue, setPointFilterValue] = useState<PointFilter>('충전');
```

2024-10-12 09:25 UTC, yujo11 commented on src/pages/MyPage/index.tsx
> +            )}
`isEdit`에 따라 달라지는 분기가 많은데요. 아예 Edlit 상태의 컴포넌트를 별도로 만들어서 하나의 분기로 값들이 달라지게 하면 코드 읽기가 조금 더 좋아질거 같네요

2024-10-13 07:48 UTC, minji2219 commented on src/components/spot/map/index.tsx
>    return (
넵!

2024-10-13 07:50 UTC, minji2219 commented on src/components/spot/storelist/index.tsx
> +    category === '카테고리 선택'
넵 다른 카테고리들은 코드처럼 배열에 넣어서 사용하고, "카테고리 선택" 문자열만 상수화, Enum으로 사용하면 될까요?

2024-10-13 07:50 UTC, minji2219 commented on src/components/spot/map/index.tsx
> +        content={<div></div>}
넵 다음주에 작성할 예정입니다!

2024-10-13 07:51 UTC, minji2219 commented on src/provider/Location/index.tsx
> +      localStorage.getItem('location') ||
넵 감사합니다!

2024-10-13 09:37 UTC, dlawlghks commented on src/components/common/Background/index.tsx
> +`;
넵 적용해보겠습니다 ㅎㅎ

2024-10-14 08:26 UTC, hojeong26 commented on src/pages/PointPage/index.tsx
> +  const [pointFilterValue, setPointFilterValue] = useState('충전');
이번주에 적용해보겠습니다!

2024-10-14 08:39 UTC, yujo11 approved these changes

2024-10-14 08:39 UTC, merged