8주차 Review PR
kakao-tech-campus-2nd-step3/Team14_FE pull request #54
Opened 2024-10-25 09:09 UTC by minji2219

## ✨ PR 내용

💻민지: 모집폼 구현, 스팟페이지 버튼 동작 추가 #45  
💻호정: 주문 내역 상세페이지(방장 구현) #48 
💻지환: 결제 페이지 구현 #50 

## ✏ 리뷰받고 싶은 내용

2024-10-26 07:25 UTC, yujo11 requested changes
코멘트들 확인 부탁드려요 ~

고생 많으셨습니다 ㅎㅎ

2024-10-26 07:25 UTC, yujo11 commented on src/components/OrderHistory/OrderListItem.tsx
> +          {price != null ? `결제금액: ${price}P` : ``}
`!=` 연산자로 비교를 하신 이유가 있을까요? `undefined`와 `null`을 모두 검증하려는 목적이었다면 아래처럼 간단하게 코드를 작성해도 괜찮을거 같네용

```suggestion
          {price ? `결제금액: ${price}P` : ``}
```

2024-10-26 07:25 UTC, yujo11 commented on src/components/OrderHistory/OrderListItem.tsx
> +          {price != null ? `결제금액: ${price}P` : ``}
아 혹시 `0`이 들어왔을 때는 결제금액을 표시해주기 위함이었나요?

2024-10-26 07:25 UTC, yujo11 commented on src/components/OrderHistoryDetail/OrderHistoryDetailItem.tsx
> +          </Text>
아래처럼 작성하지 않아도 잘 표시되나요..?

```suggestion
          <Text>
            {`${deliveryName}'님이 ${stringPrice}P 결제 완료했습니다.`}
          </Text>
```

2024-10-26 07:25 UTC, yujo11 commented on src/components/common/Modal/AlertDialog.tsx
> +  };
`let`을 사용하는 대신 아래처럼 코드를 작성해 볼 수도 있을거 같네요
```suggestion
  const btnBgColor = () => {
    switch(type) {
        case("complete"):
            return ~
         case ("warning"):
             return ~
         default: 
             return ~ 
     }
  };
```

2024-10-26 07:25 UTC, yujo11 commented on src/components/common/MyPoint/index.tsx
> +        {[5000, 10000, 20000, 30000].map((amount) => (
큰 숫자는 아래처럼 numeric separotr를 활용해보셔도 좋을거 같아요
```suggestion
        {[5_000, 10_000, 20_000, 30_000].map((amount) => (
```

2024-10-26 07:25 UTC, yujo11 commented on src/components/spot/RecruitDialog/index.tsx
> +    console.log(data);
불필요한 코드는 commit 할 때 점검하고 지워보셔도 좋을거 같아요

2024-10-26 07:25 UTC, yujo11 commented on src/components/spot/RecruitDialog/PickupModal.tsx/SearchBar.tsx
> +  };
여기는 코드가 조금 복잡해 보이는데 라이브러리에서 강제되는 사용법이 있는건가요?

2024-10-27 16:11 UTC, hojeong26 commented on src/components/OrderHistory/OrderListItem.tsx
> +          {price != null ? `결제금액: ${price}P` : ``}
아 저런 방법이 있다는걸 생각 못했습니다..!

2024-10-27 16:14 UTC, hojeong26 commented on src/components/OrderHistoryDetail/OrderHistoryDetailItem.tsx
> +          </Text>
문제없이 잘 표시 됩니다!

2024-10-28 06:30 UTC, minji2219 commented on src/components/common/Modal/AlertDialog.tsx
> +  };
오 수정하도록 하겠습니다.😄

2024-10-28 06:30 UTC, minji2219 commented on src/components/spot/RecruitDialog/index.tsx
> +    console.log(data);
넵!

2024-10-28 06:32 UTC, minji2219 commented on src/components/spot/RecruitDialog/PickupModal.tsx/SearchBar.tsx
> +  };
넵 검색했을 때, 해당 검색된 결과의 위도 경도의 범위를 저장하기 위해서는
검색할 단어로 찾고,
bounds 객체 생성해서, 각 위도 경도를 bounds에 넣어줘야하더라구요

2024-10-28 09:15 UTC, yujo11 approved these changes
시간이 되어서 PR을 병합하겠습니다 이번에 반영하지 못 한 내용은 다음 작업 때 포함시켜도 좋을거 같아요 고생 많으셨습니다 ~ 👍

2024-10-28 09:15 UTC, merged