9주차 Review PR
kakao-tech-campus-2nd-step3/Team14_FE pull request #64
Opened 2024-11-01 14:14 UTC by minji2219

pr제목 -> 관련 이슈 #4

## 📌 관련 이슈

프론트 CI 속도 개선

## ✨ PR 내용

프론트 CI 속도 개선했음!

2024-11-02 05:41 UTC, yujo11 requested changes
안녕하세요 이번 주도 고생 많으셨습니다 ~~

>프론트엔드에서 인가 코드를 통해 토큰을 발급받고 이를 이용해 API 요청을 하는 방식도 괜찮은 방식인지 궁금합니다!!

코드를 보고 개선되었으면 하는 부분이 있어 코멘트를 남겼는데요. 해당 코멘트를 확인해주시면 좋을거 같습니다!

>카테고리별 사진들을 서버에서 받지 않고, 현재 처럼 프론트에서 저장해서 뿌려주는 방식이 괜찮은지 궁금합니다.

넵 괜찮아 보여요 다만 이런 이미지들이 많아지면 번들 사이즈가 커질 수 있으니 나중에는 별도의 CDN에 업로드 해두고 가져오는 방법도 고려해보시면 좋을거 같네요 ㅎㅎ

2024-11-02 05:41 UTC, yujo11 commented on src/api/instance/index.ts
> +export const queryClient = new QueryClient({
queryClient 정의하는 곳과 axios instance를 정의하는 곳은 분리를 해도 좋을거 같네요 ㅎㅎ

2024-11-02 05:41 UTC, yujo11 commented on src/components/OrderHistory/OrderListItem.tsx
> +          {price ? `결제금액: ${price}P` : null}
👍 👍 👍

2024-11-02 05:41 UTC, yujo11 commented on src/components/common/MyPoint/index.tsx
> +        {[5_000, 10_000, 20_000, 30_000].map((amount) => (
👍 👍 👍

2024-11-02 05:41 UTC, yujo11 commented on src/components/common/Modal/AlertDialog.tsx
>      }
👍 👍 👍

2024-11-02 05:41 UTC, yujo11 commented on src/components/spot/storelist/selectCategory.tsx
> +    <Selector onChange={(e) => handleChange(e)}>
소소하게 아래처럼 적어주셔도 좋겠네요 ㅎㅎ

```suggestion
    <Selector onChange={handleChange}>
```

2024-11-02 05:41 UTC, yujo11 commented on src/pages/LoginPage/index.tsx
> +      axios
`instance`를 추상화 해둔거 같은데 여기에서는 `axios`를 그대로 사용하는 이유가 있나요?

2024-11-02 05:41 UTC, yujo11 commented on src/pages/LoginPage/index.tsx
> +        })
서버의 응답헤더로 cookie가 set되는 방법을 사용하시면 더 좋을거 같아요

브라우저의 값은 변조하기 쉽기 때문에 `httpOnly`, `Secure` 옵션으로 브라우저에서는 cookie의 값을 변경하지 못 하도록 하는 방법을 많이 사용하는데 해당 방법을 찾아보시면 좋을거 같아요. 이 부분은 서버 팀원 분들과도 같이 얘기해보시면 좋겠네요

2024-11-02 07:54 UTC, minji2219 commented on src/api/instance/index.ts
> +export const queryClient = new QueryClient({
넵!

2024-11-04 10:34 UTC, yujo11 approved these changes
이번 PR은 merge하곘습니다 ~~

2024-11-04 10:34 UTC, merged