10주차 Review PR
kakao-tech-campus-2nd-step3/Team14_FE pull request #78
Opened 2024-11-08 11:40 UTC by minji2219

## ✨ PR 내용

💻호정: FE 배포 준비 및 배포 진행
💻지환: 로그인, 로그아웃, 회원가입 기능 구현(통신 진행)
💻민지: 통신을 위한 hook 생성, api 대기

## ✏️리뷰 받고 싶은 내용

- BE에서 개별로 API를 배포했습니다. 이럴 땐, BASE_URL 설정보단, 요청할 때마다 full url을 보내는 방법이 맞을까요?

2024-11-09 06:49 UTC, yujo11 requested changes
안녕하세요 벌써 마지막 리뷰네요 ㅎㅎ

그동안 고생 많으셨습니다 주고받았던 리뷰들이 여러분들에게 조금이라도 도움이 되었으면 좋겠네요

>BE에서 개별로 API를 배포했습니다. 이럴 땐, BASE_URL 설정보단, 요청할 때마다 full url을 보내는 방법이 맞을까요?

이 부분은 코멘트로 남겼습니다!

>통신하는 코드(함수)는 별도의 hook으로 생성하는 것이 좋을지, 요청 보내는 페이지 컴포넌트에서 하는 것이 좋을지 궁금합니다!

상황마다 달라질 수도 있지만 분리했을 때의 장점과 단점을 먼저 생각해보시면 좋을거 같아요. 어떤 고민을 하셨는지 남겨주시면 추가로 코멘트 남기겠습니다

>현재 위치 조회하는 것을 '브라우저 위치로'를 읽는 것으로 조회하는 방식인데요. 정확하지 않을 때도 많나요?

정확하지 않을 때도 많습니다. 브라우저의 위치 정보를 가져오면 wifi 나 현재 네트워크 정보, IP등 통해 위치를 가져오게 되는데요.  대략적인 위치를 파악하는데 용이 할 수는 있겠지만 정밀도가 필요하다면 이런 방법으로는 정확한 위치를 파악하기는 어려울거라고 생각해요 

거기에 추가로 유저가 위치 정보 공유를 해야하고, VPN 등에 연결되어 있으면 위치가 매우 부정확해 질 수도 있구요

2024-11-09 06:49 UTC, yujo11 commented on src/api/instance/index.ts
> +// const BASE_URL = 'http://3.34.191.43';
이 부분이 PR 본문에서 질문 주신 부분인거 같은데요

>BE에서 개별로 API를 배포했습니다. 이럴 땐, BASE_URL 설정보단, 요청할 때마다 full url을 보내는 방법이 맞을까요?


BASE_URL은 보통 변하지 않기 떄문에 instance에 default 값을 세팅해두고 사용하는게 일반적인 방법인거 같아요 ㅎㅎ

보통 env에 따라 분기를 줘서 자동으로 들어가게 세팅을 해두는거 같아요

ex)

```ts
const BASE_URL = {
   dev: '...',
   beta: '...',
   prod: '...;
}

baseUrl = BASE_URL[env]
```

2024-11-09 06:49 UTC, yujo11 commented on src/components/features/Layout/Header.tsx
> +  };
cookie를 브라우저에서 컨트롤 하시는 이유가 있을까요?

2024-11-09 06:49 UTC, yujo11 commented on src/components/features/Layout/Header.tsx
> +      navigate('/');
요 path도 상수화 해서 사용하심 좋을거 같네요

2024-11-09 06:49 UTC, yujo11 commented on src/components/features/Layout/Header.tsx
> +      Cookies.remove('access_token');
요런 key 값도 상수화가 되면 좋겠네요

2024-11-09 06:55 UTC, dlawlghks commented on src/components/features/Layout/Header.tsx
> +  };
백엔드에서 자동으로 쿠키를 저장하도록 설정하는 중인데, 잘 되지 않아서 임시로 쿠키를 수동으로 관리했습니다! 백엔드 설정이 완료되면 바로 수정하겠습니다!

2024-11-11 10:23 UTC, yujo11 approved these changes
고생 많으셨어요 ~~

2024-11-11 10:23 UTC, merged