3주차 Review PR
kakao-tech-campus-2nd-step3/Team14_FE pull request #8
Opened 2024-09-20 12:55 UTC by minji2219

## 📌 관련 이슈

필요한 컴포넌트 구현

## ✨ PR 내용

- 헤더(메뉴바) 컴포넌트 구현
- 주문내역 리스트 아이템 컴포넌트 구현
- 모달창 구현

2024-09-21 09:49 UTC, yujo11 requested changes
안녕하세요 ~

아직은 구현 된 코드가 많지 않아 리뷰 남길 내용이 많지 않았는데요. 앞으로 리뷰를 위해 궁금한 부분들에도 질문 남겼으니 확인하고 같이 답변 남겨주시면 좋을거 같습니다 ㅎㅎ

>Weekly 브랜치 ->Develop브랜치 -> Master 브랜치로 PR보내고 각각 merge 할 때 rebase로 머지 해야하나요? 아니면 기본 값으로 머지하면 될까요? branch목록에서 ahead, behind 때문에 뭔가 잘못 merge가 된 것 같습니다...

정확히 어떤 문제를 겪고 있는지는 이해 하지 못 했는데요.

rebase와 merge의 차이를 찾아보시고 현재 팀 상황에서 어떤 방법이 더 적절할지 고민해보고 결정하시면 좋을거 같습니다 

>저희 조는 모달의 종류가 alert식으로 뜨는 작은 모달과 폼 작성식으로 뜨는 큰 모달이 존재하는데요. 작은 모달은 상단에 헤더바를 추가했습니다. 코드 작성한 것 처럼 title 부분에 small, big인 경우 나눠서 작성하는 코드가 괜찮을까요?

코멘트로도 남겼는데 구현 방식에 정답은 없으나 일관 되고 깔끔한 코드를 위해 `<HeaderBar>`에서 size를 받아 분기를 주는 방식도 고려해보시면 좋을거 같네요 ㅎㅎ

---

고생 많으셨습니다 ~~ 👍

2024-09-21 09:49 UTC, yujo11 commented on .eslintrc.json
> +  //airbnb사용, prettier과 충돌 나는것은 무시
주석을 남기실거면 `.json` 대신 `.eslitrc.js` 파일을 이용하셔도 좋을거 같네요 ㅎㅎ

2024-09-21 09:49 UTC, yujo11 commented on .github/ISSUE_TEMPLATE/issue--이슈-템플릿.md
👍 👍 👍

2024-09-21 09:49 UTC, yujo11 commented on craco.config.js
create-react-app을 사용하신 이유가 궁금하네용 ㅎㅎ

2024-09-21 09:49 UTC, yujo11 commented on public/index.html
> +<html lang="en">
소소하지만 이런 부분도 신경써주시면 좋을거 같네요 ㅎㅎ

2024-09-21 09:49 UTC, yujo11 commented on public/index.html
> +  <head>
head안에 들어가는 meta 태그들도 어떤 역할을 하는지 찾아보시고 프로젝트 성격에 맞게 세팅해보시면 좋을거 같습니다 ㅎㅎ

2024-09-21 09:49 UTC, yujo11 commented on src/styles/globalStyle.ts
> +};
색상 미리 정의해두는거 좋네요 ㅎㅎ

2024-09-21 09:49 UTC, yujo11 commented on src/components/OrderListItem.tsx
> +        <span style={{ color: '#7E7E7E' }}>
어떤 상황에서 inline으로 style을 적용하고 어떤 상황에서 styled 컴포넌트를 선언해서 사용할지 기준이 있을까요?

2024-09-21 09:49 UTC, yujo11 commented on src/components/common/Modal/SmallModalContent.tsx
어떤 파일에서는 styled 로직이 상단에 있고, 어떤 파일에서는 하단에 있는데요. 전체적인 코드 컨벤션을 통일해주시면 좋을거 같아요

2024-09-21 09:49 UTC, yujo11 commented on src/components/common/Modal/SmallModalContent.tsx
styled파일을 별도로 두지 않고 하나의 파일에 모두 작성하신 이유가 있을까요?

2024-09-21 09:49 UTC, yujo11 commented on src/components/common/Modal/SmallModalContent.tsx
> +const Content = styled.div`
후에 import해서 사용하는 컴포넌트와 styled component를 구분하기 위해 prefix 적용을 고민해보셔도 좋을거 같아요

ex)

```tsx
<Card> // <- 외부에서 가져온 컴포넌트
  <_Container> // <- 스타일만 정의한 컴포넌트는 `_` prefix를 사용하여 구분
     { ... }
  </_Container>
</Card>
```

2024-09-21 09:49 UTC, yujo11 commented on src/components/common/Modal/index.tsx
> +              )}
ModalBox처럼 style component에서 분기를 줘서 처리를 해줘도 좋을거 같네요 

```suggestion
                <HeaderBar size={size}>{title}</BigHeaderBar>
```

2024-09-21 09:49 UTC, yujo11 commented on src/components/common/Modal/index.tsx
> +        <Overlay>
Modal 외부 영역을 클릭했을 때 Modal이 닫히도록 구현하면 사용성이 더 좋아질거 같네용 ㅎㅎ

2024-09-21 09:49 UTC, yujo11 commented on src/components/common/Modal/index.tsx
> +const SmallHeaderBar = styled.div`
소소하게 각 선언문 사이에 개행이 하나씩 들어가면 코드 보기가 한결 좋을거 같네요

2024-09-21 09:49 UTC, yujo11 commented on src/components/features/Layout/Header.tsx
> +  z-index: 9999;
이런 z-idnex나

2024-09-21 09:49 UTC, yujo11 commented on src/components/features/Layout/Header.tsx
> +  background-color: #059770;
이런 색상들도 미리 상수화해서 사용하시면 좋을거 같네요 ㅎㅎ

2024-09-21 09:49 UTC, yujo11 commented on src/components/common/Modal/SmallModalContent.tsx
`SmallModalContent`라는 이름이 직관적으로 느껴지지 않는데요.

dialog, confirm, snackbar등 Modal에 흔히 사용되는 여러 이름들이 있는데 다른 디자인 시스템들(Antd, MUI 등)에서는 어떤 이름으로 이런 컴포넌트를 부르고 있는지 참고해보셔도 좋을거 같아요.

추가로 이런 디자인 시스템들은 다양한 상황에 유연하게 대응하기 위한 설계를 잘 해둔 부분이 많은데요. 어떤 Prop을 받고, 어떻게 구현되어 있는지도 같이 참고해보시면 좋을거 같네요 ㅎㅎ

2024-09-22 07:20 UTC, minji2219 commented on craco.config.js
프로젝트 준비 시간이 여유 없어서 간단하게 cra로 세팅 했습니다..!!

2024-09-22 10:06 UTC, hojeong26 commented on src/components/OrderListItem.tsx
> +        <span style={{ color: '#7E7E7E' }}>
적용할 style이 길지 않아서 inline으로 적용했습니다.

2024-09-23 09:44 UTC, merged

2024-09-23 09:54 UTC, dlawlghks commented on src/components/features/Layout/Header.tsx
> +  background-color: #059770;
넵 ㅎㅎ 피드백 감사합니다! 말씀해주신 대로 값들을 상수화하는 방향으로 개선해보겠습니다 !